-- nvim --headless -u NONE -i NONE -n -c "luafile configs/editor/neovim/klcm_test.lua"
package.path = "configs/editor/neovim/?.lua;" .. package.path
local klcm = require("klcm")
local api = vim.api
local notices, checks = {}, 0
vim.notify = function(message) notices[#notices + 1] = message end
vim.o.swapfile = false
vim.o.hidden = true
vim.o.showmode = false
vim.o.shortmess = vim.o.shortmess .. "s"

local function equal(expected, actual, label)
  checks = checks + 1
  if vim.env.KLCM_TEST_TRACE then
    io.stderr:write(checks .. " " .. label .. "\n")
  end
  assert(vim.deep_equal(expected, actual),
    label .. ": expected " .. vim.inspect(expected) .. ", got " .. vim.inspect(actual))
end

local thread
local function resume()
  local ok, err = coroutine.resume(thread)
  if not ok then
    io.stderr:write(tostring(err) .. "\n" .. debug.traceback(thread) .. "\n")
    vim.cmd("cquit 1")
  end
end

local function input(text)
  api.nvim_input(text)
  vim.defer_fn(resume, 20)
  coroutine.yield()
end

local function lines()
  return api.nvim_buf_get_lines(0, 0, -1, false)
end

local function fresh(text, column)
  input("<Esc>")
  vim.cmd("enew!")
  api.nvim_buf_set_lines(0, 0, -1, false, type(text) == "table" and text or { text })
  api.nvim_win_set_cursor(0, { 1, column or 0 })
  input("i")
  equal("i", api.nvim_get_mode().mode, "fresh insert mode")
end

local function signal(key)
  input(key)
end

thread = coroutine.create(function()
  vim.keymap.set("n", "<C-A-F1>", ":echo 'old mapping'<CR>", { silent = true })
  local old = vim.fn.maparg("<C-A-F1>", "n", false, true)
  klcm.setup()
  equal(36, #klcm.actions, "36 semantic actions")
  local registry = vim.fn.json_decode(table.concat(vim.fn.readfile("configs/editor/actions.json"), "\n"))
  local ids, prefixes = {}, { nav = "<C-A-F", select = "<C-A-S-F", edit = "<C-S-F" }
  for _, action in ipairs(registry.actions) do
    ids[#ids + 1] = action.id
    local lhs = prefixes[action.bank] .. action.slot .. ">"
    for _, mode in ipairs({ "i", "n", "s" }) do
      equal("KLCM " .. action.id, vim.fn.maparg(lhs, mode, false, true).desc,
        action.id .. " registry transport in " .. mode)
    end
  end
  table.sort(ids)
  equal(36, #ids, "36 registry actions")
  equal(ids, klcm.actions, "exact action IDs match shared registry")
  klcm.setup()
  equal("KLCM move.left", vim.fn.maparg("<C-A-F1>", "n", false, true).desc, "idempotence")

  fresh("abc")
  signal("<C-A-F4>")
  equal({ 1, 1 }, api.nvim_win_get_cursor(0), "insert right")
  input("X")
  equal({ "aXbc" }, lines(), "type at exact insertion boundary")
  signal("<C-A-F8>")
  input("!")
  equal({ "aXbc!" }, lines(), "line end insertion")
  signal("<C-A-F7>")
  input("^")
  equal({ "^aXbc!" }, lines(), "line start insertion")

  fresh("α😀z")
  signal("<C-A-F4>")
  equal({ 1, 2 }, api.nvim_win_get_cursor(0), "Unicode right")
  signal("<C-A-S-F4>")
  equal("s", api.nvim_get_mode().mode, "explicit Select mode")
  input("Q")
  equal({ "αQz" }, lines(), "Unicode selection replaced by typing")
  equal("i", api.nvim_get_mode().mode, "typing leaves Select for Insert")
  signal("<C-A-F1>")
  signal("<C-A-S-F1>")
  input("R")
  equal({ "RQz" }, lines(), "backward Unicode selection")

  fresh("abcd")
  signal("<C-A-S-F4>")
  signal("<C-A-S-F4>")
  input("X")
  equal({ "Xcd" }, lines(), "extend selection")
  fresh("abcd")
  signal("<C-A-S-F4>")
  signal("<C-A-S-F1>")
  equal("i", api.nvim_get_mode().mode, "collapse selection")
  input("X")
  equal({ "Xabcd" }, lines(), "collapsed selection insertion")
  fresh({ "abc", "xyz" })
  signal("<C-A-S-F2>")
  input("Q")
  equal({ "Qxyz" }, lines(), "selection includes newline")
  equal("", vim.wo.virtualedit, "selection restores virtualedit")
  fresh({ "é", "next" })
  signal("<C-A-F1>")
  equal({ 1, 0 }, api.nvim_win_get_cursor(0), "left clamps at line start")
  signal("<C-A-F8><C-A-F4>")
  equal({ 1, 2 }, api.nvim_win_get_cursor(0), "right clamps at Unicode line end")
  signal("<C-A-S-F4>")
  equal("i", api.nvim_get_mode().mode, "selection right clamps at line end")
  signal("<C-A-F2><C-A-F7><C-A-F1>")
  equal({ 2, 0 }, api.nvim_win_get_cursor(0), "left does not cross newline")
  signal("<C-A-S-F4><C-S-F12>")
  equal("i", api.nvim_get_mode().mode, "cancel selection resumes insertion")
  equal({ 2, 1 }, api.nvim_win_get_cursor(0), "cancel preserves active insertion endpoint")
  input("X")
  equal({ "é", "nXext" }, lines(), "typing after cancel inserts without replacement")
  vim.o.selection = "exclusive"
  fresh("abc")
  signal("<C-A-S-F4>")
  input("Q")
  equal({ "Qbc" }, lines(), "selection respects prior exclusive option")
  equal("exclusive", vim.o.selection, "selection option restored")
  vim.o.selection = "inclusive"

  fresh("")
  signal("<C-A-F1><C-A-F4><C-A-F6><C-S-F3>")
  equal({ "" }, lines(), "empty buffer boundaries")
  input("é")
  signal("<C-A-F10>")
  signal("<C-A-F4>")
  input("!")
  equal({ "é!" }, lines(), "EOF Unicode insertion")

  fresh("foo.bar  baz qux")
  signal("<C-A-F6>")
  equal({ 1, 3 }, api.nvim_win_get_cursor(0), "small word punctuation start")
  signal("<C-A-F6>")
  equal({ 1, 4 }, api.nvim_win_get_cursor(0), "small word after punctuation")
  signal("<C-A-F5>")
  equal({ 1, 3 }, api.nvim_win_get_cursor(0), "previous punctuation word")
  vim.fn.setreg('"', "keep unnamed")
  vim.fn.setreg("a", "keep named")
  vim.fn.setreg("1", "keep numbered")
  vim.fn.setreg("-", "keep small delete")
  local undo_levels = vim.bo.undolevels
  signal("<C-S-F3>")
  equal({ "foobar  baz qux" }, lines(), "delete current boundary through word start")
  equal("keep unnamed", vim.fn.getreg('"'), "unnamed register preserved")
  equal("keep named", vim.fn.getreg("a"), "named register preserved")
  equal("keep numbered", vim.fn.getreg("1"), "numbered register preserved")
  equal("keep small delete", vim.fn.getreg("-"), "small delete register preserved")
  equal(undo_levels, vim.bo.undolevels, "local undo option preserved")

  fresh("one two three four five")
  signal("<C-S-F4>")
  equal({ "four five" }, lines(), "delete three words")
  signal("<C-S-F6>")
  equal({ "" }, lines(), "repeat destructive action")
  signal("<C-S-F1>")
  equal({ "four five" }, lines(), "repeat separate undo unit")
  signal("<C-S-F1>")
  equal({ "one two three four five" }, lines(), "first deletion separate undo unit")
  signal("<C-S-F2>")
  equal({ "four five" }, lines(), "redo")

  fresh("hello world", 2)
  signal("<C-S-F3>")
  equal({ "heworld" }, lines(), "midword delete starts at insertion boundary")
  fresh({ "één", "два three" })
  signal("<C-S-F3>")
  equal({ "два three" }, lines(), "Unicode cross-line delete")

  fresh("before (outer (inner) tail) after", 16)
  signal("<C-S-F5>")
  equal({ "before (outer () tail) after" }, lines(), "innermost parens preserve delimiters")
  input("new")
  equal({ "before (outer (new) tail) after" }, lines(), "parens insertion position")
  fresh("no parentheses", 3)
  signal("<C-S-F5>")
  equal({ "no parentheses" }, lines(), "missing parens safe")
  assert(notices[#notices]:match("No enclosing"))
  fresh("(unmatched", 4)
  signal("<C-S-F5>")
  equal({ "(unmatched" }, lines(), "unmatched parens safe")
  fresh("()", 1)
  signal("<C-S-F5>")
  input("λ")
  equal({ "(λ)" }, lines(), "empty parentheses insertion")
  fresh({ "start (a", "b) end" }, 7)
  signal("<C-S-F5>")
  equal({ "start () end" }, lines(), "multiline parentheses")

  fresh({ "α😀", "xyz", "", "last" })
  signal("<C-A-F4><C-A-F4><C-A-F2>")
  equal({ 2, 2 }, api.nvim_win_get_cursor(0), "vertical Unicode columns")
  signal("<C-A-F12>")
  equal({ 3, 0 }, api.nvim_win_get_cursor(0), "next paragraph")
  signal("<C-A-F10>")
  equal({ 4, 4 }, api.nvim_win_get_cursor(0), "document end")
  signal("<C-A-F11>")
  equal({ 3, 0 }, api.nvim_win_get_cursor(0), "previous paragraph")
  signal("<C-A-F9>")
  equal({ 1, 0 }, api.nvim_win_get_cursor(0), "document start")
  signal("<C-A-F2><C-A-F3>")
  equal({ 1, 0 }, api.nvim_win_get_cursor(0), "up movement")
  signal("<C-A-F6>")
  equal({ 1, 2 }, api.nvim_win_get_cursor(0), "Unicode small-word start")
  signal("<C-A-F6><C-A-F6>")
  equal({ 3, 0 }, api.nvim_win_get_cursor(0), "word-next stops on empty paragraph")

  fresh({ "one", "two", "three" })
  input("<Esc>ggG")
  equal({ 3, 0 }, api.nvim_win_get_cursor(0), "native jump forward")
  signal("<C-S-F11>")
  equal({ 1, 0 }, api.nvim_win_get_cursor(0), "history back uses native jumplist")
  equal("i", api.nvim_get_mode().mode, "history back resumes insertion")

  fresh("first second first")
  signal("<C-S-F7>")
  equal("c", api.nvim_get_mode().mode, "visible search command line")
  input("second<Esc>")
  equal({ "first second first" }, lines(), "cancel search does not edit")
  equal("i", api.nvim_get_mode().mode, "cancel search returns insert")
  signal("<C-A-F8><C-S-F7>")
  input("notfound<C-S-F12>")
  equal("i", api.nvim_get_mode().mode, "semantic cancel closes search prompt")
  equal({ 1, 18 }, api.nvim_win_get_cursor(0), "cancel restores EOF insertion boundary")
  signal("<C-S-F7>")
  equal(true, klcm.dispatch("interaction.cancel"), "public prompt cancellation")
  input("")
  equal("i", api.nvim_get_mode().mode, "public cancellation returns Insert")
  equal({ 1, 18 }, api.nvim_win_get_cursor(0), "public cancellation preserves insertion boundary")
  signal("<C-A-F7>")
  signal("<C-S-F7>")
  input("first<CR>")
  equal({ 1, 13 }, api.nvim_win_get_cursor(0), "native search accepted")
  signal("<C-S-F8>")
  equal({ 1, 0 }, api.nvim_win_get_cursor(0), "next search wraps")
  signal("<C-S-F9>")
  equal({ 1, 13 }, api.nvim_win_get_cursor(0), "previous search wraps")
  fresh("x x")
  vim.fn.setreg("/", "x")
  signal("<C-A-F8><C-S-F9>")
  equal({ 1, 2 }, api.nvim_win_get_cursor(0), "backward search includes final character before EOL boundary")
  signal("<C-S-F9>")
  equal({ 1, 0 }, api.nvim_win_get_cursor(0), "backward search from match skips current match")
  signal("<C-A-F8>")
  vim.fn.setreg("/", "missing")
  signal("<C-S-F8>")
  equal({ 1, 3 }, api.nvim_win_get_cursor(0), "failed forward search preserves EOL insertion boundary")
  signal("<C-S-F9>")
  equal({ 1, 3 }, api.nvim_win_get_cursor(0), "failed backward search preserves EOL insertion boundary")
  vim.fn.setreg("/", [[\%[]])
  signal("<C-S-F9>")
  equal({ 1, 3 }, api.nvim_win_get_cursor(0), "invalid regex preserves insertion boundary")
  fresh("safe dd text")
  input("<C-S-F7>dd<CR>")
  equal({ "safe dd text" }, lines(), "queued search text is never Normal-mode commands")
  equal({ 1, 5 }, api.nvim_win_get_cursor(0), "queued search locates match")
  equal("i", api.nvim_get_mode().mode, "queued accepted search returns insertion")
  input("<C-S-F7>text<CR>dd")
  equal({ "safe dd ddtext" }, lines(), "queued post-search typing never executes Normal dd")
  input("<C-S-F7>dd<Esc>Q")
  equal({ "safe dd ddQtext" }, lines(), "queued cancelled search resumes insertion before typing")
  fresh("end")
  input("<C-A-F8><C-S-F7>nonexistent<CR>Q")
  equal({ "endQ" }, lines(), "queued submitted missing search preserves EOL insertion boundary")
  equal("i", api.nvim_get_mode().mode, "failed submitted search returns Insert")
  fresh("end")
  input("<C-A-F8><C-S-F7>\\(<CR>Q")
  equal({ "endQ" }, lines(), "queued invalid submitted regex preserves EOL insertion boundary")
  fresh("x end")
  vim.o.wrapscan = false
  input("<C-A-F8><C-S-F7>x<CR>Q")
  equal({ "x endQ" }, lines(), "queued nowrapscan failure preserves EOL insertion boundary")
  vim.o.wrapscan = true
  fresh("x")
  vim.v.errmsg = "earlier unrelated error"
  input("<C-A-F8><C-S-F7>x<CR>Q")
  equal({ "Qx" }, lines(), "successful wraparound at original clamped character uses match boundary")
  equal("earlier unrelated error", vim.v.errmsg, "successful search does not mistake earlier error for failure")

  fresh("abc words", 1)
  local formatter = api.nvim_create_autocmd("InsertLeave", {
    once = true, buffer = 0,
    callback = function() api.nvim_buf_set_lines(0, 0, -1, false, { "😀 formatted" }) end,
  })
  signal("<C-S-F3>")
  equal({ "😀 formatted" }, lines(), "InsertLeave mutation cancels stale destructive range")
  equal("i", api.nvim_get_mode().mode, "formatter cancellation resumes insertion")
  assert(notices[#notices]:match("text changed"))
  input("Q")
  equal({ "Q😀 formatted" }, lines(), "formatter cancellation uses valid UTF-8 boundary")
  pcall(api.nvim_del_autocmd, formatter)
  fresh("original words")
  local source_window = api.nvim_get_current_win()
  api.nvim_create_autocmd("InsertLeave", {
    once = true, buffer = 0, callback = function() vim.cmd("vsplit") end,
  })
  signal("<C-S-F3>")
  equal({ "original words" }, lines(), "InsertLeave window switch cancels destructive action")
  assert(api.nvim_get_current_win() ~= source_window)
  equal("i", api.nvim_get_mode().mode, "window switch cancellation resumes insertion safely")
  input("<Esc>")
  vim.cmd("close")
  signal("<C-S-F10>")
  assert(notices[#notices]:match("No LSP"))
  signal("<C-S-F12>")
  equal("i", api.nvim_get_mode().mode, "semantic cancel resumes insertion")
  input("<Esc>")
  equal("n", api.nvim_get_mode().mode, "Escape stays Normal")
  equal(false, klcm.dispatch("not.an.action"), "unknown action rejected")

  vim.bo.modifiable = false
  equal(false, klcm.dispatch("edit.delete_word"), "unmodifiable excluded")
  vim.bo.modifiable = true
  vim.bo.readonly = true
  equal(false, klcm.dispatch("edit.delete_word"), "readonly excluded")
  vim.bo.readonly = false
  vim.bo.buftype = "nofile"
  equal(false, klcm.dispatch("move.left"), "special buffer excluded")
  vim.bo.buftype = ""
  local native_calls = 0
  vim.keymap.set("n", "<C-A-F4>", function() native_calls = native_calls + 1 end)
  vim.bo.buftype = "nofile"
  input("<C-A-F4>")
  equal(1, native_calls, "global shortcut works in special buffer")
  vim.bo.buftype = ""
  vim.bo.readonly = true
  input("<C-A-F4>")
  equal(2, native_calls, "global shortcut works in readonly buffer")
  vim.bo.readonly = false
  vim.bo.modifiable = false
  input("<C-A-F4>")
  equal(3, native_calls, "global shortcut works in unmodifiable buffer")
  vim.bo.modifiable = true
  input("<C-A-F4>")
  equal(3, native_calls, "eligible transition reattaches semantic shortcut")
  equal("i", api.nvim_get_mode().mode, "eligible transition restores semantic movement")
  input("<Esc>")
  local ignored = vim.o.eventignore
  vim.o.eventignore = "OptionSet"
  vim.bo.readonly = true
  vim.o.eventignore = ignored
  input("<C-A-F4>")
  equal(4, native_calls, "eligibility guard forwards original shortcut when OptionSet is suppressed")
  vim.bo.readonly = false
  local command_calls = 0
  vim.keymap.set("c", "<C-S-F12>", function()
    command_calls = command_calls + 1
    return "native"
  end, { expr = true })
  input(":<C-S-F12><C-u><Esc>")
  equal(1, command_calls, "native command-line shortcut is untouched outside own prompt")
  input("i<C-S-F7>dd<C-S-F12>")
  equal(1, command_calls, "own search temporarily overrides cancel shortcut")
  equal("i", api.nvim_get_mode().mode, "own semantic search cancel still works")
  input("<Esc>:<C-S-F12><C-u><Esc>")
  equal(2, command_calls, "native command-line shortcut restored immediately after own prompt")
  klcm.teardown()
  equal(old.rhs, vim.fn.maparg("<C-A-F1>", "n", false, true).rhs, "previous mapping restored")
  equal("", vim.fn.maparg("<C-A-F2>", "i"), "new mapping removed")
  input(":<C-S-F12><C-u><Esc>")
  equal(3, command_calls, "native command-line mapping retained through teardown")
  input("<C-A-F4>")
  equal(5, native_calls, "global shortcut retained through teardown")
  vim.keymap.del("c", "<C-S-F12>")
  vim.keymap.del("n", "<C-A-F4>")
  klcm.teardown()
  equal(false, klcm.dispatch("move.left"), "dispatch after teardown rejected")
  klcm.setup({ mappings = { ["move.right"] = "<F6>" }, insert_on_enter = true })
  input(":enew!<CR>")
  equal("i", api.nvim_get_mode().mode, "opt-in buffer entry")
  input("<Esc>")
  equal("n", api.nvim_get_mode().mode, "entry policy does not force InsertEnter")
  input("iabc<F6>X")
  equal({ "abcX" }, lines(), "custom transport")
  input("<Esc>")
  klcm.teardown()

  local called = false
  vim.keymap.set("n", "<F6>", function() called = true end, { silent = true })
  klcm.setup({ mappings = { ["move.right"] = "<F6>" } })
  klcm.teardown()
  input("<F6>")
  equal(true, called, "Lua callback mapping restored")

  vim.keymap.set("n", "<F7>", ":let g:klcm_global = 1<CR>")
  vim.keymap.set("n", "<F7>", ":let g:klcm_local = 1<CR>", { buffer = 0 })
  klcm.setup({ mappings = { ["move.right"] = "<F7>" } })
  klcm.teardown()
  input("<F7>")
  equal(1, vim.g.klcm_local, "local shadow mapping retained")
  vim.keymap.del("n", "<F7>", { buffer = 0 })
  input("<F7>")
  equal(1, vim.g.klcm_global, "shadowed global mapping restored")

  vim.keymap.set("c", "<C-S-F12>", "local-cancel", { buffer = 0 })
  klcm.setup()
  fresh("text")
  vim.keymap.set("c", "<C-S-F12>", "local-cancel", { buffer = 0 })
  signal("<C-S-F7>")
  input("text<C-S-F12>")
  equal("local-cancel", vim.fn.maparg("<C-S-F12>", "c"), "local command-line mapping restored after own prompt")
  local replacement_calls = 0
  vim.keymap.set("n", "<C-A-F4>", function() replacement_calls = replacement_calls + 1 end, { buffer = 0 })
  input("<Esc>")
  klcm.teardown()
  input("<C-A-F4>")
  equal(1, replacement_calls, "teardown preserves user mapping installed after setup")
  vim.keymap.del("n", "<C-A-F4>", { buffer = 0 })
  vim.keymap.del("c", "<C-S-F12>", { buffer = 0 })

  klcm.setup()
  fresh("one two three")
  input("<Esc>")
  klcm.dispatch("edit.delete_word")
  klcm.dispatch("edit.delete_word")
  equal({ "three" }, lines(), "consecutive programmatic normal actions")
  input("<Esc>")
  signal("<C-S-F1>")
  equal({ "two three" }, lines(), "programmatic action undo unit")
  signal("<C-S-F1>")
  equal({ "one two three" }, lines(), "programmatic first undo unit")
  signal("<C-A-S-F4>")
  klcm.teardown()
  equal("n", api.nvim_get_mode().mode, "teardown exits its Select mode")
  equal("inclusive", vim.o.selection, "teardown restores selection setting")
  equal("", vim.wo.virtualedit, "teardown restores virtualedit")
  print("KLCM Neovim: " .. checks .. " assertions passed")
  vim.cmd("qa!")
end)
vim.schedule(resume)
vim.defer_fn(function()
  io.stderr:write("Timed out after " .. checks .. " assertions\n")
  vim.cmd("cquit 1")
end, 15000)
