package keyboard_config

var Layer0Left = KeycodeLayerHalf{
	KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_TRANSPARENT, // function keys
	ST_MACRO_Screenshot, KC_QUOTE, KC_DOUBLE_QUOTE, KC_MINUS, KC_EQUAL, KC_SLASH, KC_TRANSPARENT, // number keys
	KC_ControlAltDelete, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_TRANSPARENT,
	KC_ESCAPE, KC_A, KC_S, KC_D, KC_F, KC_G, KC_TRANSPARENT,
	TO(0), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_TRANSPARENT,
	KC_TRANSPARENT, RGUI(KC_Z), RGUI(KC_S), RGUI(KC_C), RGUI(KC_V), MO(1), KC_TRANSPARENT,
	KC_TRANSPARENT, KC_BACKSPACE, KC_LEFT_SHIFT, KC_LEFT_ALT, KC_LEFT_CTRL, KC_LEFT_GUI, KC_TRANSPARENT,
}
var Layer0Right = KeycodeLayerHalf{
	KC_TRANSPARENT, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, // function keys
	KC_TRANSPARENT, KC_BACKSLASH, KC_LEFT_BRACKET, KC_RIGHT_BRACKET, KC_LEFT_PAREN, KC_RIGHT_PAREN, KC_TRANSPARENT, // number keys
	KC_TRANSPARENT, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_H, KC_J, KC_K, KC_L, KC_DOT, KC_ENTER,
	KC_TRANSPARENT, KC_N, KC_M, KC_QUOTE, KC_DOUBLE_QUOTE, KC_COMMA, TO(2),
	KC_TRANSPARENT, MO(1), KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_ESCAPE, KC_TAB, KC_RIGHT_GUI, KC_RIGHT_SHIFT, KC_SPACE, KC_TRANSPARENT,
}

var Layer1Left = KeycodeLayerHalf{
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, // function keys
	KC_TRANSPARENT, ST_MACRO_Anglebrakets, ST_MACRO_CurlyBraces, KC_TRANSPARENT, KC_TRANSPARENT, LSFT(KC_5), KC_TRANSPARENT,
	KC_TRANSPARENT, KC_QUOTE, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, LSFT(KC_4), KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, LSFT(KC_3), KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, LSFT(KC_2), KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
}

var Layer1Right = KeycodeLayerHalf{
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, // function keys
	KC_TRANSPARENT, LSFT(KC_6), KC_TRANSPARENT, KC_0, ST_MACRO_SquareBraces, ST_MACRO_Parenthesis, KC_TRANSPARENT,
	KC_TRANSPARENT, LSFT(KC_7), KC_1, KC_2, KC_3, KC_DOUBLE_QUOTE, KC_TRANSPARENT,
	KC_TRANSPARENT, LSFT(KC_8), KC_4, KC_5, KC_6, KC_TRANSPARENT, KC_TRANSPARENT,
	KC_TRANSPARENT, LSFT(KC_BACKSLASH), KC_7, KC_8, KC_9, KC_TRANSPARENT, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_0, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
}

// Enegram Layout with the following mods.
// Flipped
// R and H swap, R is on the home row in energram-ES
var Layer2Left = KeycodeLayerHalf{
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, // function keys
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_V, KC_W, KC_D, KC_L, KC_QUOTE, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_N, KC_S, KC_T, KC_R, KC_COMMA, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_P, KC_F, KC_M, KC_H, KC_Z, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_Z, KC_Q, KC_Z, KC_Q, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
}
var Layer2Right = KeycodeLayerHalf{
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, // function keys
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_DOUBLE_QUOTE, KC_U, KC_O, KC_Y, KC_B, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_DOT, KC_A, KC_E, KC_I, KC_C, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_Q, KC_K, KC_J, KC_X, KC_G, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
	KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
}
