// Code generated by "stringer -type=macrocode"; DO NOT EDIT.

package keyboard_config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PLACEHOLDER-0]
	_ = x[ST_MACRO_Screenshot-1]
	_ = x[ST_MACRO_Anglebrakets-2]
	_ = x[ST_MACRO_Parenthesis-3]
	_ = x[ST_MACRO_SquareBraces-4]
	_ = x[ST_MACRO_CurlyBraces-5]
}

const _macrocode_name = "PLACEHOLDERST_MACRO_ScreenshotST_MACRO_AnglebraketsST_MACRO_ParenthesisST_MACRO_SquareBracesST_MACRO_CurlyBraces"

var _macrocode_index = [...]uint8{0, 11, 30, 51, 71, 92, 112}

func (i macrocode) String() string {
	if i >= macrocode(len(_macrocode_index)-1) {
		return "macrocode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _macrocode_name[_macrocode_index[i]:_macrocode_index[i+1]]
}
